; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ── Setari comune tuturor environmentelor ─────────────────────────────────────
[env]
platform = atmelavr
board = ATmega328P
framework = arduino
monitor_speed = 57600
extra_scripts = generate_bin.py
upload_protocol = custom
upload_command = /home/balica/.platformio/packages/tool-avrdude/avrdude -c xplainedmini -p atmega328p -P usb -U flash:w:.pio/build/${PIOENV}/firmware.hex:i

[common]
inc_flags =
	-I${PROJECT_SRC_DIR}/drivers
	-I${PROJECT_SRC_DIR}/lib

; ── Bootloader ────────────────────────────────────────────────────────────────
; BOOT_ADR = 0x7000 = 4KB boot section (BOOTSZ=00 in fuse)
[env:ATmega328P]
build_src_filter = -<*> +<boot/main.c> +<boot/flash.S> +<drivers/sd.c> +<drivers/spi.c> +<lib/pff.c> +<drivers/twi.c>
build_flags =
	${common.inc_flags}
	-DBOOT_ADR=0x7000
	-Wl,--section-start=.text=0x7000

; ── Jocuri ────────────────────────────────────────────────────────────────────
[env:TicTacToe]
build_src_filter = -<*> +<games/tictactoe/main_tictactoe.c> +<games/tictactoe/tictactoe.c> +<drivers/twi.c> +<drivers/ssd1306.c> +<drivers/adc.c> +<drivers/joystick.c> +<drivers/sd.c> +<drivers/spi.c>
build_flags =
	${common.inc_flags}
	-I${PROJECT_SRC_DIR}/games/tictactoe

[env:Snake]
build_src_filter = -<*> +<games/snake/main_snake.c> +<games/snake/snake.c> +<drivers/twi.c> +<drivers/ssd1306.c> +<drivers/adc.c> +<drivers/joystick.c> +<drivers/sd.c> +<drivers/spi.c>
build_flags =
	${common.inc_flags}
	-I${PROJECT_SRC_DIR}/games/snake
